GET http://localhost:8000/api
Accept: application/json

###
# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/api/v1/merchants
Accept: application/json

###
